### ISSUE TITLE
Improve Error Message

### ISSUE THREAD

**Issue by grantcarthew** [aurelia/event-aggregator#15]
Hi,
I just made a mistake in my application that caused the EA to report this error:
```js
ERROR [event-aggregator] TypeError: subscribers[i] is not a function(…)
```

After adding some console statements into the `aurelia-event-agregator` source code I discovered my `EA.subscribe` call was not passing in a function because I had not made the function yet. Simple mistake but made harder due to the error message.

It is an obvious mistake now that I look at it and the error message should have had me looking in the right direction, but it's late, I was coming back to old code, and you know how it goes.

Could this error message be more descriptive? 

The function call is at line 57 of `event-aggregator/src/index.js`.

Please kill this if you think I am being a little nuts.

**Comment by Gheoan** [comment]
Clicking the `(…)` at the end of the error message should show more details about the error. (ex: call stack)

**Comment by EisenbergEffect** [comment]
Can you show me some code that produced this error? If I could see that...we could provide a better message for that fail case.

**Comment by grantcarthew** [comment]
I still don't know if this is worth time or effort.
My code was this:
```js
this.eventAggregator.subscribe('PictureAdd', this.addFile)
```
I had not added this.addFile to the VM, so.... dumb mistake.
So the event aggregator subscription had `undefined` as the callback method.

**Comment by EisenbergEffect** [comment]
We could check to make sure the subscribe function wasn't undefined....and throw an error. That would be pretty simple. What do you think?

**Comment by grantcarthew** [comment]
Fail on subscription rather than call would have helped I recon Rob.

**Comment by EisenbergEffect** [comment]
Sounds like a plan. We'll get it done.

**Comment by grantcarthew** [comment]
You (and the team) are amazing. Loving Aurelia. Thanks mate.
