### ISSUE TITLE
Subscribe to event with function call

### ISSUE THREAD

**Issue by larsfjerm** [aurelia/event-aggregator#16]
Shouldn't this work?

Within the constructor:
`this.myProperty = 'Test value';`
`eventAggregator.subscribe(SomeEvent, this.handleEvent);`

```
handleEvent(event) {
      let data = event.data;
      console.log(this.myProperty );
}
```

I can access the event object, but when I try to access `this.myProperty` I get an error: `ERROR [event-aggregator] TypeError: Cannot read property 'myProperty' of null`.

**Comment by larsfjerm** [comment]
Works:
`eventAggregator.subscribe(SomeEvent, event => this.handleEvent(event));`

**Comment by Gheoan** [comment]
In JS, the value of `this`depends on how the function is called. In this case it is called from inside [`Handler`](https://github.com/aurelia/event-aggregator/blob/e1661a00ff9894891a59cd8dfd3f5d83964de158/src/index.js#L13).

However that does not justify the use of Function.prototype.call`.

You can work around by using arrow function or `Finction.prototype.bind` (this.handleEvent.bind(this)).

**Comment by tomkersten** [comment]
I know this issue is closed, but, I'm still slightly confused as to why this code wouldn't work:

```javascript
export class NavBar {
  ...
  attached() {
    this.eventAggregator.subscribe(CurrentUserSet, message => {
      console.log('received user set message');
      debugger;
      this.user = message.user; // `this` is null...why?
    })
  }
}
```

**Comment by Gheoan** [comment]
@EisenbergEffect discussed with @tomkersten on gitter about his code. Shouldn't `this` be the `NavBar` instance because he is using arrow function? Does the `Function.prototype.call` from [here](https://github.com/aurelia/event-aggregator/blob/e1661a00ff9894891a59cd8dfd3f5d83964de158/src/index.js#L13) cause this behaviour?

**Comment by StrahilKazlachev** [comment]
A transpiler problem with arrow functions? **call** and **apply** should not affect arrow functions **this**.
