### ISSUE TITLE
Feat proposal: decorators

### ISSUE THREAD

**Issue by Scapal** [aurelia/event-aggregator#17]
I made a couple of decorators for EventAggregator:
You put a `@handle` decorator on the event handler, and you put a `@subscribe`on the `attached()` to register all the subscriptions on attach:

Here is a usage sample:

```javascript
@subscribe
attached() {
}

@unsubscribe
detached() {
}

@handle(‘store:users:changed’)
usersChanged(msg) {
     // do something
}

@handle(‘store:other_event’)
otherEventHandler(event) {
     // do something
}
```

I'm not sure about the names, maybe `@handleEvent`, `@subscribeEventHandlers`... would be better.

Here is the current code:
```javascript
import {Metadata} from './metadata.js'
import {Container} from 'aurelia-framework';
import {EventAggregator} from 'aurelia-event-aggregator';

export function handle(...properties) {
	return function(target, key, descriptor) {
		// Get a unique (using Symbol) metadata store to avoid collisions
		let metadata = Metadata.getOrCreateMetadata(target);
		// Store each event / handler pairs
		properties.forEach( prop => metadata.handlers.push( {msg: prop, handler: key} ));
				
		return descriptor;
	}
}

export function subscribe() {
	let eventAggregator = Container.instance.get(EventAggregator);
	
	return function(target, key, descriptor) {
		// Override the decorated method in order to subscribe to all the registered events
		return {
			...descriptor,
			value: function() {
				console.log('subscribe');
				let metadata = Metadata.getOrCreateMetadata(target);
				let handlers = metadata.handlers;
				for(let i=0; i < handlers.length; ++i) {
					metadata.subscriptions.push(eventAggregator.subscribe(handlers[i].msg, (...args) => {
						this[handlers[i].handler].apply(this, args)
					}));
				}
				// Call the original method
				descriptor.value.apply(this, arguments);	
			}
		}
	}
} 

export function unsubscribe() {
	return function(target, key, descriptor) {
		// Override the decorated method in order to dispose of all subscriptions.
		return {
			...descriptor,
			value: () => {
				let metadata = Metadata.getOrCreateMetadata(target);
				metadata.subscriptions.forEach( (subscription) => {
					subscription.dispose();
				});
				// Call the original method
				descriptor.value.apply(this, arguments);	
			}
		}
	}
} 
```
and the metadata.js:
```javascript
export class Metadata {
    static metadata = Symbol('eventAggregatorMetadata');
	
    static getOrCreateMetadata(target) {
        if(target[this.metadata] === undefined) {
            target[this.metadata] = new Metadata();
        }

        return target[this.metadata];
    }

    static exists(target) {
        return target[this.metadata] !== undefined && target[this.metadata] instanceof Metadata;
    }

    constructor() {
        this.handlers = [];
	this.subscriptions = [];
    }
}
```

What do you think, should I PR this as it is? What about the names?

**Comment by Scapal** [comment]
I guess I'll have to remove relying on `Symbol`, where should I put it in aurelia metadata, `metadata.eventAggregator`?
I liked the use of `Symbol`as it is an elegant way to avoid naming collisions.

**Comment by EisenbergEffect** [comment]
Would it be possible to build this as a plugin rather than bake it into our EA? If so, you could do some feature detection in your plugin to see if Symbols were available and if not, just polyfill it inside the plugin. What do you think?

**Comment by PWKad** [comment]
I really like this idea.  Originally I thought a plugin would be best but considering how small the footprint would be I'm not sure because it does seem like it would add a ton of value.

Is the `subscribe` and `unsubscribe` necessary?  It seems like the decorators could register some private property and dispose of themselves on detached.

**Comment by Scapal** [comment]
Since it is very small I thought it would be better inside your EA. We could remove Symbols dependencies if you agree on a property name I could use, like target.eaHandling.

**Comment by Scapal** [comment]
@PWKad how would you do that without changing the `aurelia-templating` `Controller`? The `@subscriber`and `@unsubscribe` are here to avoid doing so?
I could directly modify `attached()` and `detached()` if they are defined in the VM **before** using `@handle`. If not, a further definition of them in the VM code would override any definition.

**Comment by PWKad** [comment]
Not 100% sure just thinking out loud that it would be nice to have less imports.  Perhaps the name `subscribe` would be a bit mis-leading as well, is that rooted in flux as a normal naming pattern?

**Comment by EisenbergEffect** [comment]
I'm hesitant to grow the core framework. Since it's something that can work as a simple plugin, I would favor that. In our documentation on the EA we could have a section featuring your plugin, if you were willing to help  maintain the docs.

**Comment by Scapal** [comment]
@PWKad I used `@subscribe` because it does `subscribe` on the EventAggregator, could be `@subscribeEventHandlers`.

**Comment by EisenbergEffect** [comment]
I'm going to close this for now. I'd really love to see this as a plugin. We'd be happy to feature you on our official blog with an article on how to use it. Just let us know when you are ready.

**Comment by timfish** [comment]
This would certainly fit the "convention over configuration" philosophy. I use the EA a lot to keep my components loosely coupled but have a lot of boilerplate code just to subscribe and unsubscribe when attached/detached. Maybe after v1 is out of beta this can be considered?

**Comment by EisenbergEffect** [comment]
I think it's a good fit for a plugin and one we'd be happy to feature :)

**Comment by timfish** [comment]
Load and clear Rob! :)
