### ISSUE TITLE
Ability to subscribe / publish array of channels

### ISSUE THREAD

**Issue by VagyokC4** [aurelia/event-aggregator#18]
Would like to be able to publish / subscribe to multiple channels at the same time.

For example:
```
    this.eventAggregator.publish(['channel1','channel2','channel3'], payload);
```
or
```
    this.eventAggregator.subscribe(['channel1','channel2','channel3'], payload => {
        ...
    });
```

My use case deals more with the subscribe side, but for symmetry the publish should be possible as well.

**Comment by jdanyow** [comment]
hi @VagyokC4, here's an example of how you could add that capability: https://gist.run/?id=d4556db1d61c69fb40a1

**Comment by VagyokC4** [comment]
@jdanyow So this should be done as a one-off per project thing, and not implemented in the core EA?

**Comment by jdanyow** [comment]
not sure- was just offering a workaround.  Could provide more information about your use-case and why this feature would be helpful?  This kind of info really helps when the core team and the rest of the community review feature requests.

**Comment by VagyokC4** [comment]
I'm getting an error implementing this work-around.  
```
system.src.js:4597 GET http://localhost:45635/dist/aurelia-event-aggregator.js?bust=1457227039154 404 (Not Found)
```

My use case is simple.. I want to publish events on different channels to keep them separate, but there are two modules that I want to listen to an array of channels and have them all run the same function.  As it is I have a bunch of subscriptions all executing the same code.

```
        this.subscription = this.eventAggregator.subscribe([
            'notification-hub:OfferExtended',
            'notification-hub:OfferRetracted',
            'notification-hub:request-updated'
        ], payload => {
            self.reloadData();
        });
```

**Comment by jdanyow** [comment]
odd- that's the error you'd get if you hadn't done `jspm install aurelia-event-aggregator`.  But if that were the case your other code that uses the event aggregator wouldn't work...

**Comment by VagyokC4** [comment]
Yeah.. its weird.. I just checked with the older code and it was working before adding this to main.js.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
jspm_packages/npm/core-js@1.2.6/client/shim.min.js:1773 Error: XHR error (404 Not Found) loading http://localhost:45635/dist/aurelia-event-aggregator.js?bust=1457227495702
	Error loading http://localhost:45635/dist/aurelia-event-aggregator.js as "aurelia-event-aggregator" from http://localhost:45635/dist/main.js
    at o (http://localhost:45635/jspm_packages/system.js:4:12694)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:45635/jspm_packages/system.js:4:13219)
```

**Comment by VagyokC4** [comment]
```
jspm install aurelia-event-aggregator
     Updating registry cache...
     Looking up npm:aurelia-event-aggregator
     Looking up npm:aurelia-logging
ok   Up to date - aurelia-event-aggregator as npm:aurelia-event-aggregator@^1.0.0-beta.1.1.1 (1.0.0-beta.1.1.1)
ok   Install tree has no forks.

ok   Install complete.
```

**Comment by jdanyow** [comment]
no- I'm completely stumped.  Clearly you've installed it.  After examining the 404 error message, I can see you didn't misspell the import.  Any chance you have `./` in your `import {EventAggregator} from './aurelia-event-aggregator';` statement? That's the only other thing I can think of.  Should be `from 'aurelia-event-aggregator';`.

**Comment by VagyokC4** [comment]
Okay.. not sure.. but its working now.  Work-around and all :)

So is this a valid enough use case to get it into the core EA?

**Comment by EisenbergEffect** [comment]
I'm not sure we should add this to the core for now. Thanks for the ideas though!
