### ISSUE TITLE
Debouncing subscribed callback invocation

### ISSUE THREAD

**Issue by heruan** [aurelia/event-aggregator#19]
A useful feature of this library would be the subscription to an event with an optional debounce/throttle timing.

**Comment by EisenbergEffect** [comment]
We really don't want to expand this library, but rather keep it very basic. I think this type of feature could be built on top of the basic pieces we have in place.

It's important we don't add everything under the sun into the core or the library will become to large for practical use, especially on mobile devices. Consider creating a plugin or even just a gist that shows how to add this feature on top of the base.
