### ISSUE TITLE
eventAggregator subscribe 2x router:navigation:complete

### ISSUE THREAD

**Issue by jedd-ahyoung** [aurelia/event-aggregator#20]
@flieks commented on [Wed Mar 16 2016](https://github.com/aurelia/router/issues/310)

Hi,

How can i subscribe in 2 different places to an event from the router ?
The second subscription is overriding the first one now..
so the first one is never called

Greetings
Felix

---

@jedd-ahyoung commented on [Sun Apr 24 2016](https://github.com/aurelia/router/issues/310#issuecomment-214047998)

@flieks Can you create a test case for this, using the router navigation event and a separate event? This may be an issue with the event aggregator.

**Comment by EisenbergEffect** [comment]
No feedback from the OP or repro, so closing this since it's highly unlikely to be a bug in the EA.
