### ISSUE TITLE
event-aggregator not working with dependency injection 

### ISSUE THREAD

**Issue by emcga** [aurelia/event-aggregator#22]
When injecting the event-aggregator, and trying to publish an event, I receive the following error...

Uncaught TypeError: Cannot read property 'publish' of undefined.

also, when I console.log(eventAggregator) "undefined" is printed.

I have been going crazy trying to figure out why this isn't working... Any help would be greatly appreciated.

Here is my code...

```javascript
import {inject} from 'aurelia-framework';
import {UIDialog} from 'aurelia-ui-framework';
import {EventAggregator} from 'aurelia-event-aggregator';

@inject(EventAggregator)
export class DeleteConfirmation extends UIDialog {

  title = "confirm delete operation";
  content = "Are you sure you want to delete this item?";
  info = "";
  modal = true;
  resize = false;
  height = 100;

  constructor(eventAggregator) {
    super();
    this.eventAggregator = eventAggregator;
    console.log(eventAggregator);
  }

  no(){
    this.eventAggregator.publish('confirm-delete-dialog-close', {result: false});
    super.close();
  }

  yes(){
    this.eventAggregator.publish('confirm-delete-dialog-close', {result: true});
    super.close();
  }
}
```

**Comment by EisenbergEffect** [comment]
What does your app bootstrap code look like? The EA is an optional plugin. It's included if you are using the router or the standard configuration, but if you aren't, it's not actually installed.

**Comment by emcga** [comment]
Thanks for the fast response! 

Here is what I'm loading in my main.js file

Also, I'm using the router. Do I still need to activate the EventAggregator plugin in main.js?

Thanks for your help.

```javascript
import {Aurelia} from 'aurelia-framework';
import {UIValidationStrategy} from "aurelia-ui-framework";
import {HttpClientConfiguration} from "aurelia-fetch-client";

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-ui-framework', function(config){
      // AppKey for local/session storage key prefix
      config.App.Key = 'App';
      // Application Title
      config.App.Title = 'Warehouse Management System';
      // Application Version
      config.App.Version = '0.0.1';

      // HTTPClient Base API URL
      config.Http.BaseUrl = './';
      // HTTPClient Extra Headers
      config.Http.Headers = {
        'X-API-VERSION': '2'
      };
      // HTTPClient Send Basic Authorization Header
      config.Http.AuthorizationHeader = false;
    })
    .plugin('aurelia-validation', (config) => {
      config.useViewStrategy(new UIValidationStrategy());
    });

  //HttpClientConfiguration.


  //Uncomment the line below to enable animation.
  //aurelia.use.plugin('aurelia-animator-css');

  //Anyone wanting to use HTMLImports to load views, will need to install the following plugin.
  //aurelia.use.plugin('aurelia-html-import-template-loader')

  aurelia.start().then(a => a.setRoot());
}

```

**Comment by emcga** [comment]
Also, I should probably mention that I did a "jspm install aurelia-event-aggregator" with hopes of getting it to work. I also tried importing the EventAggregator from 'aurelia-framework', and 'aurelia-event-aggregator'.

**Comment by jdanyow** [comment]
I don't think `this` is what it's supposed to be if you're getting `Uncaught TypeError: Cannot read property 'publish' of undefined`.

change your `no` and `yes` methods to this and I bet it works:

```js
no = () => {
    this.eventAggregator.publish('confirm-delete-dialog-close', {result: false});
    super.close();
  }

  yes = () => {
    this.eventAggregator.publish('confirm-delete-dialog-close', {result: true});
    super.close();
  }
```

We would need to see how `no` and `yes` are being used to provide more info.

**Comment by emcga** [comment]
yes() and no() are just event handlers attached to button click events. I'll try your suggested changes and see if it works. 

Thank you.

**Comment by jdanyow** [comment]
share the code you're using to bind to the button click events

**Comment by emcga** [comment]
@jdanyow Still receiving the same error message after implementing your suggested changes.

**Comment by emcga** [comment]
```html
<ui-button label="Yes" success click.trigger="yes()"></ui-button>
<ui-button label="No" danger click.trigger="no()"></ui-button>
```

**Comment by jdanyow** [comment]
looks good to me....

**Comment by jdanyow** [comment]
ah- how is `DeleteConfirmation` being instantiated?  Not with `new DeleteConfirmation()` right?

**Comment by emcga** [comment]
Ohhh, yes. I did create an instance of the view model first. It was because of an issue I was having with the ui framework. 

```javascript

    let viewModel = new DeleteConfirmation();                                                                                   
    viewModel.content = "delete contact "+ contact.FName + "?";                                                                 
    viewModel.info = "The contact will only be removed from this lot supplier. The contact will not be deleted from the database."
                                                                                                                                
    this.dialogService.show(viewModel);                                                                                         
```

Should I let DI handle the instantiation of the view model also?

**Comment by emcga** [comment]
Totally overlooked that, my apologies.

**Comment by emcga** [comment]
So I changed the code to let the DI handle the creation of the view model instance, and it worked flawlessly!! I guess I should take a break from coding and take a walk or something! Sorry to take your time on this issue. 

Thank you @jdanyow and @EisenbergEffect for your help.

**Comment by jdanyow** [comment]
nice! glad you got it working :+1:
