### ISSUE TITLE
Is it possible to subscribe to multiple or all the events?

### ISSUE THREAD

**Issue by stefek99** [aurelia/event-aggregator#23]
Looking at the source: https://github.com/aurelia/event-aggregator/blob/master/src/index.js#L86

```
subscribe(event: string | Function, callback: Function): Subscription {
```

Subscribe accepts a string...

Thinking what is the best the way to subscribe to a couple of events without copy & paste too much...

**Comment by EisenbergEffect** [comment]
The EA supports an api for subscribing to single events. If you have to subscribe a single handler to multiple events frequently, I would recommend that you write a little helper method to facilitate that process.
