### ISSUE TITLE
There is no way to unsubscribe an event

### ISSUE THREAD

**Issue by inmchfw** [aurelia/event-aggregator#33]
**I'm submitting a feature request**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Linux (distro)

* **Node Version:**
8.4.0

* **NPM Version:**
5.5

* **Browser:**
Chrome 60.1

* **Language:**
TypeScript 2.40

**Current behavior:**

Our use case is: A controller will subscribe a event in attached() and when it happens, a dialog will open. Now, the controller detaches and attaches again, when the event happens, two of the same dialog opens.

There is no way to un-subscribe a handler. Hence if a controller subscribe an event, and the controller detaches and attaches again, there are two handlers registered on the eventLookup.

**Expected/desired behavior:**
* **What is the expected behavior?**

Un-subscribe event on detached
so that subscribe on attached() method.

* **What is the motivation / use case for changing the behavior?**
Well, this could improve our code. We are now hacking into to eventLookup and manually remove the handler in detached method.

**Comment by StrahilKazlachev** [comment]
Are you saying that calling `.dispose()` on the subscription object does nothing?

**Comment by inmchfw** [comment]
Oh I see! I have just tried it using `dispose()` method and it works like a charm! Thank you!!
