### ISSUE TITLE
question - Subscribe by interface to match multiple event types?

### ISSUE THREAD

**Issue by diegohb** [aurelia/event-aggregator#34]
event model:
```
class PaneSizeToggledEvent : IMyEvent {
}
```

publisher:
`this._eventAgg.publish(new PaneSizeToggledEvent(!pShow));`

consumer:
```
 this._eventAgg.subscribe(IMyEvent,
            (pEvent: IMyEvent) => {
                this._logger.debug("Instance of one of my events", pEvent);
            });

```

is this supported ?  also, how does the event type subscription work if I subscribe using just type PaneSizeToggledEvent , is it typeof and just the name of the class ?

**Comment by StrahilKazlachev** [comment]
1. Please *format* the issue according to the *issue template*.
2. You can't subscribe by *interface* since there is no such thing as an *interface* at run time.
3. It uses `instanceof`.

**Comment by Alexander-Taran** [comment]
```
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : 2months } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by EisenbergEffect** [comment]
Can't do anything about this since TS erases all interfaces at compile-time.
