### ISSUE TITLE
Feature Request - Method to get all Event Names

### ISSUE THREAD

**Issue by ghiscoding** [aurelia/event-aggregator#43]
**I'm submitting a feature request**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
12.14.0

* **NPM Version:**
6.13.4

* **JSPM OR Webpack AND Version**
WebPack

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all

**Current behavior:**
There are no ways of accessing all the events, internally I can see the `eventLookup` object being used but there are no methods that we can call to get this object/list and it seems to be a private object.

**Expected/desired behavior:**
It would be nice to have a method to at least access the `eventLookup` so that we could perhaps do an `Object.keys` on it, or even better a method that would return a string array of all the events that were created. 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
For my use case, I have a plugin library [Aurelia-Slickgrid](https://github.com/ghiscoding/aurelia-slickgrid) and I would like to loop through all the events I used in the plugins and for some of them (with a certain prefix or keyword) re-expose them to the outside through a dispatch event. So it's kind of a way to take some internal plugin events and expose some of them to the outside (user of my plugin). Currently, to do this, I have to go through every event that I want to re-expose 1 by 1 and do a dispatch event from there, but it would be so useful to just loop through the list and filter out only the ones I want to re-expose. 

Use Case Example
```ts
// current usage, I have about 10 types of Event I would like to re-expose
this.pluginEa.subscribe('excelExportService:beforeExport', (triggered: boolean) => {
   this.elm.dispatchEvent(DOM.createCustomEvent(`asg-on-before-excel-export`, {
          bubbles: true,
          detail: triggered
   }));
});
```

```html
// View
<aurelia-slickgrid 
    grid-id="grid1" 
    column-definitions.bind="columnDefinitions" 
    grid-options.bind="gridOptions"
    dataset.bind="dataset" 
    asg-on-before-excel-export.delegate="spinner = true"
    asg-on-after-excel-export.delegate="spinner = false">
  </aurelia-slickgrid>
```
So if I could loop through all Events that start with `asg`, I could assign a `dispatchEvent` and be done with it, instead of having to type them 1 by 1.

**Comment by EisenbergEffect** [comment]
@ghiscoding I think we could take a PR for something like this. Do you want to propose and API design?

**Comment by ghiscoding** [comment]
Something along this

```ts
getAll(){
  return this.eventLookup;
}
```

and/or 
```ts
getAllEventNames() {
  return Object.keys(this.eventLookup);
}
```

I'm not sure what would happen with the ones that are of type `Function` though? 
Since I see the argument as being `event: string | Function`

**Comment by EisenbergEffect** [comment]
The EA can have either string message channels or message types. I think you would probably want two apis, one that filtered by string and one that filtered by type. If you don't really need to full internal lookup, then I'd rather not expose that.

**Comment by ghiscoding** [comment]
By looking at the code I can see that the `eventLookup` only uses string type, so both of the methods I wrote seem valid for my usage. In my case, I would use the `getAll` since I need the data returned by the callback event when triggered.

**Comment by EisenbergEffect** [comment]
Ah yes. I checked the source. I'm a bit uncomfortable exposing the internal storage. I've got another option for you, which doesn't require altering this library. What if you created a new class that extends from EventAggregator, override the subscribe method and capture the data you need in a way that you can expose it, before passing it along to the super.subscribe? Then, register your new EventAggregator under the EventAggregator key in the root DI container at startup. All your components/services will get the new version with your new feature, and we won't have to make any change to the core library or expose internal details.

**Comment by ghiscoding** [comment]
Ah that makes sense, I didn't think about that. I guess I'll do that, that is the smallest amount of work. 
Should I close the issue then?

**Comment by EisenbergEffect** [comment]
Give it a shot and after you've confirmed that it's working for you, please feel free to close this out.

**Comment by ghiscoding** [comment]
I ended up with something like the following, just in case it might help someone else

```ts
export class SlickgridEventAggregator extends EventAggregator {
  subscribers: any = {};

  getAllSubscribers() {
    return this.subscribers;
  }

  getAllEventNames() {
    return Object.keys(this.subscribers);
  }

  subscribe(event: string, callback: (data: any) => void): Disposable {
    this.subscribers[event] = callback;
    return super.subscribe(event, callback);
  }
}
```
I think I can close the issue, I ended up using something else on top of that since I don't always know early enough which event will be used.
